### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by renyijiu** [simbawus/calendar#2]
The problem can be reproduced in the demo.

![image](https://user-images.githubusercontent.com/8318266/63949405-f24f9c00-caac-11e9-97e8-aac0ecc0005a.png)

When I click on the red frame position of the picture，the console show the errors:

![image](https://user-images.githubusercontent.com/8318266/63950148-0f389f00-caae-11e9-9825-4a5401b21c47.png)

**Comment by simbawus** [comment]
thanks, I have fixed it.
