### ISSUE TITLE
onDayClick内无法使用this

### ISSUE THREAD

**Issue by ZHENGXU11** [simbawus/calendar#3]

**Comment by ZHENGXU11** [comment]
在angular中使用 onDayClick方法内部无法取到this 导致选中的日期无法传到外部使用，请问如何解决，打扰了

**Comment by simbawus** [comment]
抱歉，我不是angular用户。在react中会有需要在constructor 手动bind this的操作，不知道angular是否也一样

**Comment by ZHENGXU11** [comment]
谢谢您提供的思路 非常感谢您的回复



---原始邮件---
发件人: "simbawu"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 中午11:13
收件人: "simbawus/calendar"<calendar@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ZHENGXU11"<798396444@qq.com&gt;;
主题: Re: [simbawus/calendar] onDayClick内无法使用this (#3)



抱歉，我不是angular用户。在react中会有需要在constructor 手动bind this的操作，不知道angular是否也一样
